version: "3.8"

services:
  backend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./data:/app/data # Persist city data
    ports:
      - "8000:8000"
    command: ["npx", "json-server", "--watch", "data/cities.json", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build: .
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
