version: "3.8"

services:
  backend:
    image: node:20-alpine
    container_name: planetwander_backend
    working_dir: /app
    volumes:
      - ./data:/app/data # Persist city data
    ports:
      - "8000:8000"
    command: ["npx", "json-server", "--watch", "data/cities.json", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - caddy-net

  frontend:
    build: .
    container_name: planetwander_frontend
    ports:
      - "3002:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${VITE_API_URL} 
    env_file:
      - .env  
    networks:
      - caddy-net

networks:
  caddy-net:
    external: true